-------------------
About BigNose Linux
-------------------

  Blessed are the cheesemakers
  Blessed are the meek
  Blessed are the bignoses
  Oooh, that's nice, isn't it?
       -- from Monty Python's `The Life of Brian'

BigNose Linux is a binary Linux installation for Sun Ultra5/10 computers and is
based on the Gentoo Linux `meta-distro'.  It could work well on other Sun boxen 
too. The BigNose Linux distro is primarily intended to quickly create a LAMP-
stack web server (Linux, Apache, MySQL and PHP).

More info available here: http://bignoselinux.org

Type `help' to view the Help menu.

