---------
Help Menu
---------

At the `boot:' prompt, type one of the following:

  about           About BigNose Linux
  bignose         Boot this LiveCD
  config          Display the silo.conf file
  hardware        Help on Hardware diagnostics and configuration
  hello           Display the greeting message
  parameters      Show boot parameters
  power           Resetting and powering up
  video           Help on video mode
  halt            Enter OpenProm environment
Once in OpenProm (prompt is `ok'):
  go              Return from OpenProm to the calling environment
  boot cdrom      Reboot from the CD drive
  boot disk       Reboot from the hard disk
  help            General help on OpenProm
  help `command'  Help on a specific OpenProm command

You can also enter the OpenProm environment with the Stop+A (L1+A on some Sun
keyboards) key combination. More about OpenProm here:
http://www.gentoo.org/doc/en/gentoo-sparc-obpreference.xml

