-----------------------------------------
Setting boot parameters and powering down
-----------------------------------------

You can control and diagnose the computer with the following commands
from within the OpenProm environment (the `ok' prompt):

* Boot from CDROM
    ok boot cdrom
* Boot from a remote server 
    ok boot net [arguments - see `help']
* Boot from the primary hard disk
    ok boot disk

* Reset the system 
    ok reset-all
* Power down the system
    ok power-off

Type `help' to view Help menu.

